### ISSUE TITLE
Better default values

### ISSUE THREAD

**Issue by marcthe12** [ii8/havoc#1]
Use 80*25 by default. Since this is the default of several term programs. It also heartened that the terminal fits on screen
Also use bash as the default shell. It make life easier

**Comment by ii8** [comment]
The defaults are 80x24, AFAIK the vt100 used 24 instead of 25 so I went with that.
The shell needs to default to /bin/sh because bash is not guaranteed to be available.

You can configure both those things in havoc.cfg now though, there are some comments in there so should be simple.
Copy the file to $XDG_CONFIG_HOME or $HOME/.config for it to work everywhere and not just the current directory.
I'm think about taking the shell out of the config and only using environment TERM variable(not yet done at all).

**Comment by marcthe12** [comment]
It in fact 15*117 in havoc.cfg. I studied the code I recommend splitting the config code to separate file. It is messy at the moment

**Comment by ii8** [comment]
Yes, the examples in havoc.cfg are different from the defaults, they dont really matter, I can change them if you like.
I will eventually split things up once it gets too big, its all very much still in progress.
