### ISSUE TITLE
Support a system wide config file

### ISSUE THREAD

**Issue by ericonr** [ii8/havoc#25]
Hey there!

A install target could be added into the makefile that installs the default `havoc.cfg` into a directory like `/usr/share/havoc/` or `/etc/havoc/` (I prefer the first one). That way, if the terminal is packaged, users have a default document to use as reference. It would be interesting if it was also supported as one of the places that havoc looks for a config file.

I am interested in implementing this (would probably be quite simple) if you think it's a feature you want.

**Comment by ii8** [comment]
I don't really see why you would want that, all of the options in `havoc.cfg` are personal preference, so systemwide config isn't much use.

Example configuration can be installed in a place such as `/usr/share/examples` (on void linux, didn't check other distros) by the package manager.

Otherwise, the proper way to provide users with a reference is to add a manpage.

**Comment by ii8** [comment]
`/usr/share/havoc` would be the wrong place for configuration anyway I think: https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html
You can also see implementing systemwide config($XDG_CONFIG_DIRS) adherence is not completely trivial and makes it harder for the user to find where configuration is coming from.

**Comment by ii8** [comment]
I'm closing this, feel free to re-open if you disagree with what I said.

**Comment by ericonr** [comment]
Thanks for the quick response, sorry for my delay. I see what you mean, though! A file in `/usr/share/example` should indeed be enough.
