### ISSUE TITLE
musl: nonspacing.h has different content in upstream

### ISSUE THREAD

**Issue by matu3ba** [ii8/havoc#33]
tig shows 2019-10-12 update ctype data to unicode 12.1.0
commit e95538fa07d2b460b25ee6c2fef05f820888776d

Related question: How is the content of `tsm` folder generated?
Would be nice to put a hint or the scripts for that.

**Comment by ii8** [comment]
I updated it. All the new special emojis and whatnot never work in my terminal anyway so it won't really make a difference.

I just copy the files from musl, nothing fancy, I don't know how they generate it. It's because GNU wcwidth has problems with LOCALES iirc so I just use the musl one so havoc has consistent behavior on every libc.

libtsm also had it's own wcwidth implementation originally but it was broken so I use the musl one now.
