### ISSUE TITLE
libtsm is unmaintained since 2014. what alternatives do exist?

### ISSUE THREAD

**Issue by matu3ba** [ii8/havoc#34]
[last commits seen here](https://cgit.freedesktop.org/~dvdhrm/libtsm).

Right now there appear to be no Wayland compatible smallish terminal emulators (with relative few dependencies), ie look [here](https://www.slant.co/topics/5372/~wayland-terminal-emulators#6) and [this list](https://github.com/natpen/awesome-wayland#terminal-emulators).

What would you suggest to use/keep an eye on with rather few dependencies?

**Comment by ii8** [comment]
The libtsm used in havoc is forked from the original, has several improvements and bugfixes and is maintained by me.
I suggest you use havoc of course :), but I might be biased there. I use it everyday myself.

**Comment by matu3ba** [comment]
Sounds good to me then. Do you want to host it somewhere more prominent maybe or is that too much maintenance churn?

**Comment by ii8** [comment]
I thought about maintaining libtsm standalone if that's what you mean. I ended up not doing that because I wanted to break backward compatibility of the library API to better suit havoc.

There was an effort to maintain libtsm here https://github.com/Aetf/libtsm, but it looks like that has died since and they were bloating it up without fixing its bugs so I decided not to use that one back in the day as well.
